"""empty message

Revision ID: 36d8b323adf7
Revises: de8e7acff7ef
Create Date: 2023-06-22 19:11:16.639527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d8b323adf7'
down_revision = 'de8e7acff7ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
