"""empty message

Revision ID: 37bbde7ad5fb
Revises: 3ae005e36d6c
Create Date: 2023-06-23 02:55:40.187095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = '37bbde7ad5fb'
down_revision = '3ae005e36d6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    investmentintervalscale = ENUM('MINUTE', 'HOUR', 'DAY', name='investmentintervalscale', create_type=False)
    investmentintervalscale.create(op.get_bind(), checkfirst=True)
    op.add_column('Bots', sa.Column('investment_interval_scale', investmentintervalscale, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bots', 'investment_interval_scale')
    # ### end Alembic commands ###
