"""empty message

Revision ID: 3ae005e36d6c
Revises: aa0524bf1470
Create Date: 2023-06-22 20:07:08.962928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae005e36d6c'
down_revision = 'aa0524bf1470'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transactions', sa.Column('price', sa.DECIMAL(precision=32, scale=17), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Transactions', 'price')
    # ### end Alembic commands ###
