"""empty message

Revision ID: 45650a5987ea
Revises: f33c3a684f82
Create Date: 2023-06-13 12:59:12.855169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45650a5987ea'
down_revision = 'f33c3a684f82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bots', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_constraint('Bots_key_id_fkey', 'Bots', type_='foreignkey')
    op.drop_constraint('Bots_bot_type_id_fkey', 'Bots', type_='foreignkey')
    op.drop_constraint('Bots_stock_id_fkey', 'Bots', type_='foreignkey')
    op.create_foreign_key(None, 'Bots', 'BotTypes', ['bot_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Bots', 'Stocks', ['stock_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Bots', 'Keys', ['key_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Klines_stock_id_fkey', 'Klines', type_='foreignkey')
    op.create_foreign_key(None, 'Klines', 'Stocks', ['stock_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Transactions_bot_id_fkey', 'Transactions', type_='foreignkey')
    op.create_foreign_key(None, 'Transactions', 'Bots', ['bot_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Transactions', type_='foreignkey')
    op.create_foreign_key('Transactions_bot_id_fkey', 'Transactions', 'Bots', ['bot_id'], ['id'])
    op.drop_constraint(None, 'Klines', type_='foreignkey')
    op.create_foreign_key('Klines_stock_id_fkey', 'Klines', 'Stocks', ['stock_id'], ['id'])
    op.drop_constraint(None, 'Bots', type_='foreignkey')
    op.drop_constraint(None, 'Bots', type_='foreignkey')
    op.drop_constraint(None, 'Bots', type_='foreignkey')
    op.create_foreign_key('Bots_stock_id_fkey', 'Bots', 'Stocks', ['stock_id'], ['id'])
    op.create_foreign_key('Bots_bot_type_id_fkey', 'Bots', 'BotTypes', ['bot_type_id'], ['id'])
    op.create_foreign_key('Bots_key_id_fkey', 'Bots', 'Keys', ['key_id'], ['id'])
    op.drop_column('Bots', 'is_active')
    # ### end Alembic commands ###
