"""empty message

Revision ID: 475b6e220d5d
Revises: c7a1db56f747
Create Date: 2023-06-21 21:52:53.762157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '475b6e220d5d'
down_revision = 'c7a1db56f747'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    botstatus_enum = postgresql.ENUM('LOADING', 'RUNNING', 'STOPPED', name='botstatus', create_type=False)
    botstatus_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('Bots', sa.Column('status', botstatus_enum, nullable=True))
    op.drop_column('Bots', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bots', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Bots', 'status')
    # ### end Alembic commands ###
