"""empty message

Revision ID: 4ad95e6eb5d6
Revises: 59d27ffb406d
Create Date: 2023-05-23 23:45:02.630656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad95e6eb5d6'
down_revision = '59d27ffb406d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DataTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DataTypes_id'), 'DataTypes', ['id'], unique=True)
    op.create_table('Keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=100), nullable=True),
    sa.Column('secret_key', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Keys_id'), 'Keys', ['id'], unique=True)
    op.add_column('BotParametersTypes', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'BotParametersTypes', 'DataTypes', ['type_id'], ['id'])
    op.drop_column('BotParametersTypes', 'type')
    op.add_column('Bots', sa.Column('bot_type_id', sa.Integer(), nullable=True))
    op.add_column('Bots', sa.Column('key_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Bots', 'Keys', ['key_id'], ['id'])
    op.create_foreign_key(None, 'Bots', 'BotTypes', ['bot_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Bots', type_='foreignkey')
    op.drop_constraint(None, 'Bots', type_='foreignkey')
    op.drop_column('Bots', 'key_id')
    op.drop_column('Bots', 'bot_type_id')
    op.add_column('BotParametersTypes', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'BotParametersTypes', type_='foreignkey')
    op.drop_column('BotParametersTypes', 'type_id')
    op.drop_index(op.f('ix_Keys_id'), table_name='Keys')
    op.drop_table('Keys')
    op.drop_index(op.f('ix_DataTypes_id'), table_name='DataTypes')
    op.drop_table('DataTypes')
    # ### end Alembic commands ###
