"""empty message

Revision ID: 4aecb927d2fb
Revises: 37bbde7ad5fb
Create Date: 2023-06-23 03:38:22.127599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aecb927d2fb'
down_revision = '37bbde7ad5fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bots', sa.Column('running_mode', sa.Enum('MINUTE', 'HOUR', 'DAY', name='investmentintervalscale'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bots', 'running_mode')
    # ### end Alembic commands ###
