"""empty message

Revision ID: 59d27ffb406d
Revises: b6bf3dbdd94a
Create Date: 2023-05-16 14:07:43.036983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d27ffb406d'
down_revision = 'b6bf3dbdd94a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bots', sa.Column('stock_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Bots', 'Stocks', ['stock_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Bots', type_='foreignkey')
    op.drop_column('Bots', 'stock_id')
    # ### end Alembic commands ###
