"""empty message

Revision ID: 59eef35f1505
Revises: 5eea95d38544
Create Date: 2023-06-23 03:40:29.992661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59eef35f1505'
down_revision = '5eea95d38544'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
