"""empty message

Revision ID: 5eea95d38544
Revises: 4aecb927d2fb
Create Date: 2023-06-23 03:38:56.669541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eea95d38544'
down_revision = '4aecb927d2fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
