"""empty message

Revision ID: 7a44a31b7aa3
Revises: e42dc1ce7730
Create Date: 2023-06-22 20:04:03.744123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a44a31b7aa3'
down_revision = 'e42dc1ce7730'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bots', sa.Column('max_money_to_invest', sa.DECIMAL(precision=32, scale=17), nullable=True))
    op.add_column('Bots', sa.Column('max_level', sa.DECIMAL(precision=32, scale=17), nullable=True))
    op.add_column('Bots', sa.Column('min_level', sa.DECIMAL(precision=32, scale=17), nullable=True))
    op.add_column('Klines', sa.Column('low', sa.DECIMAL(precision=32, scale=17), nullable=True))
    op.add_column('Klines', sa.Column('high', sa.DECIMAL(precision=32, scale=17), nullable=True))
    op.add_column('Klines', sa.Column('open', sa.DECIMAL(precision=32, scale=17), nullable=True))
    op.add_column('Klines', sa.Column('close', sa.DECIMAL(precision=32, scale=17), nullable=True))
    op.add_column('Klines', sa.Column('volume', sa.DECIMAL(precision=32, scale=17), nullable=True))
    op.add_column('Transactions', sa.Column('price', sa.DECIMAL(precision=32, scale=17), nullable=True))
    op.add_column('Transactions', sa.Column('base_asset_balance', sa.DECIMAL(precision=32, scale=17), nullable=True))
    op.add_column('Transactions', sa.Column('quote_asset_balance', sa.DECIMAL(precision=32, scale=17), nullable=True))
    op.add_column('Transactions', sa.Column('base_asset_amount', sa.DECIMAL(precision=32, scale=17), nullable=True))
    op.add_column('Transactions', sa.Column('quote_asset_amount', sa.DECIMAL(precision=32, scale=17), nullable=True))
    op.add_column('Transactions', sa.Column('total_balance_in_quote_asset', sa.DECIMAL(precision=32, scale=17), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Transactions', 'total_balance_in_quote_asset')
    op.drop_column('Transactions', 'quote_asset_amount')
    op.drop_column('Transactions', 'base_asset_amount')
    op.drop_column('Transactions', 'quote_asset_balance')
    op.drop_column('Transactions', 'base_asset_balance')
    op.drop_column('Transactions', 'price')
    op.drop_column('Klines', 'volume')
    op.drop_column('Klines', 'close')
    op.drop_column('Klines', 'open')
    op.drop_column('Klines', 'high')
    op.drop_column('Klines', 'low')
    op.drop_column('Bots', 'min_level')
    op.drop_column('Bots', 'max_level')
    op.drop_column('Bots', 'max_money_to_invest')
    # ### end Alembic commands ###
