"""empty message

Revision ID: 8517dd3d5948
Revises: c201e0cbbd47
Create Date: 2023-06-23 03:41:40.865055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = '8517dd3d5948'
down_revision = 'c201e0cbbd47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    runningmode = ENUM('STATIC', 'DYNAMIC', name='runningmode', create_type=False)
    runningmode.create(op.get_bind(), checkfirst=True)
    op.add_column('Bots', sa.Column('running_mode', runningmode, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bots', 'running_mode')
    # ### end Alembic commands ###
