"""empty message

Revision ID: 881dd89106c6
Revises: fc0dfb5a64b9
Create Date: 2023-06-22 16:43:15.717621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881dd89106c6'
down_revision = 'fc0dfb5a64b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Bots_key_id_fkey', 'Bots', type_='foreignkey')
    op.create_foreign_key(None, 'Bots', 'Keys', ['key_id'], ['id'])
    op.add_column('Transactions', sa.Column('base_asset_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('Transactions', sa.Column('quote_asset_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_column('Transactions', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transactions', sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('Transactions', 'quote_asset_amount')
    op.drop_column('Transactions', 'base_asset_amount')
    op.drop_constraint(None, 'Bots', type_='foreignkey')
    op.create_foreign_key('Bots_key_id_fkey', 'Bots', 'Keys', ['key_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
