"""empty message

Revision ID: aa0524bf1470
Revises: 7a44a31b7aa3
Create Date: 2023-06-22 20:06:47.830395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0524bf1470'
down_revision = '7a44a31b7aa3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Transactions', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transactions', sa.Column('price', sa.NUMERIC(precision=32, scale=17), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
