"""empty message

Revision ID: b6bf3dbdd94a
Revises: 
Create Date: 2023-05-16 00:32:59.435325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bf3dbdd94a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BotTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_BotTypes_id'), 'BotTypes', ['id'], unique=True)
    op.create_table('Bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('some_general_attribute', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Bots_id'), 'Bots', ['id'], unique=True)
    op.create_table('Stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('dates', sa.DateTime(), nullable=True),
    sa.Column('low', sa.DECIMAL(precision=12), nullable=True),
    sa.Column('high', sa.DECIMAL(precision=12), nullable=True),
    sa.Column('open', sa.DECIMAL(precision=12), nullable=True),
    sa.Column('close', sa.DECIMAL(precision=12), nullable=True),
    sa.Column('volume', sa.DECIMAL(precision=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Stocks_id'), 'Stocks', ['id'], unique=True)
    op.create_table('BotParametersTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['bot_type_id'], ['BotTypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_BotParametersTypes_id'), 'BotParametersTypes', ['id'], unique=True)
    op.create_table('BotParametersValues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('bot_parameters_type_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['Bots.id'], ),
    sa.ForeignKeyConstraint(['bot_parameters_type_id'], ['BotParametersTypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_BotParametersValues_id'), 'BotParametersValues', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_BotParametersValues_id'), table_name='BotParametersValues')
    op.drop_table('BotParametersValues')
    op.drop_index(op.f('ix_BotParametersTypes_id'), table_name='BotParametersTypes')
    op.drop_table('BotParametersTypes')
    op.drop_index(op.f('ix_Stocks_id'), table_name='Stocks')
    op.drop_table('Stocks')
    op.drop_index(op.f('ix_Bots_id'), table_name='Bots')
    op.drop_table('Bots')
    op.drop_index(op.f('ix_BotTypes_id'), table_name='BotTypes')
    op.drop_table('BotTypes')
    # ### end Alembic commands ###
