"""empty message

Revision ID: de8e7acff7ef
Revises: 881dd89106c6
Create Date: 2023-06-22 17:17:39.873931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8e7acff7ef'
down_revision = '881dd89106c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transactions', sa.Column('base_asset_balance', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('Transactions', sa.Column('quote_asset_balance', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('Transactions', sa.Column('total_balance_in_quote_asset', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Transactions', 'total_balance_in_quote_asset')
    op.drop_column('Transactions', 'quote_asset_balance')
    op.drop_column('Transactions', 'base_asset_balance')
    # ### end Alembic commands ###
