"""empty message

Revision ID: e42dc1ce7730
Revises: 36d8b323adf7
Create Date: 2023-06-22 20:02:55.401644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e42dc1ce7730'
down_revision = '36d8b323adf7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bots', 'max_money_to_invest')
    op.drop_column('Bots', 'max_level')
    op.drop_column('Bots', 'min_level')
    op.drop_column('Klines', 'open')
    op.drop_column('Klines', 'close')
    op.drop_column('Klines', 'high')
    op.drop_column('Klines', 'low')
    op.drop_column('Klines', 'volume')
    op.drop_column('Transactions', 'base_asset_amount')
    op.drop_column('Transactions', 'price')
    op.drop_column('Transactions', 'quote_asset_balance')
    op.drop_column('Transactions', 'quote_asset_amount')
    op.drop_column('Transactions', 'base_asset_balance')
    op.drop_column('Transactions', 'total_balance_in_quote_asset')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transactions', sa.Column('total_balance_in_quote_asset', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('Transactions', sa.Column('base_asset_balance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('Transactions', sa.Column('quote_asset_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('Transactions', sa.Column('quote_asset_balance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('Transactions', sa.Column('price', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
    op.add_column('Transactions', sa.Column('base_asset_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('Klines', sa.Column('volume', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('Klines', sa.Column('low', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
    op.add_column('Klines', sa.Column('high', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
    op.add_column('Klines', sa.Column('close', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
    op.add_column('Klines', sa.Column('open', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
    op.add_column('Bots', sa.Column('min_level', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
    op.add_column('Bots', sa.Column('max_level', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
    op.add_column('Bots', sa.Column('max_money_to_invest', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
