"""empty message

Revision ID: fc0dfb5a64b9
Revises: 475b6e220d5d
Create Date: 2023-06-22 11:59:46.485676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0dfb5a64b9'
down_revision = '475b6e220d5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transactions', sa.Column('money_mode', sa.Enum('REAL', 'PAPER', 'NOT_CONFIGURED', name='botmoneymode'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Transactions', 'money_mode')
    # ### end Alembic commands ###
